WebUI/Models/MovieViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebUI.Models
{
    public class MovieViewModel
    {
        public Guid ID { get; set; }  
        
        [Required(ErrorMessage ="Campo {0} deve ser preenchido")]
        [StringLength(60, MinimumLength = 4, ErrorMessage = "{0} deve ter minimo 4 e maximo 60 caracteres")]
        [Display(Name ="Título")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Data de lancamento")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = false)]
        public DateTime ReleaseDate { get; set; }

        [Required(ErrorMessage = "Campo {0} deve ser preenchido")]
        [StringLength(60, MinimumLength = 4, ErrorMessage = "{0} deve ter minimo 4 e maximo 60 caracteres")]
        [Display(Name = "Diretor")]
        [RegularExpression(@"^[a-zA-Z ']+$", ErrorMessage ="{0} não pode conter caracteres especiais")]
        public string Director { get; set; }

        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$")]
        public decimal Gross { get; set; }

        [Required]
        [RegularExpression(@"^\d+.?\d{0,1}$", ErrorMessage = "O {0} deve conter apenas numeros positivos e apenas uma casa decimal")]
        [Range(typeof(double), "0", "10", ConvertValueInInvariantCulture = true, ErrorMessage = "O {0} deve ser entre 0 e 10.")]
        public double Rating { get; set; }

        [Display(Name ="Genero")]
        public Guid GenreID { get; set; }
        public GenreViewModel Genre { get; set; } 
        
        [Display(Name ="Picture")]
        public string ImagePath { get; set; }        
        public IFormFile ImageUpload { get; set; }        
        

        public IEnumerable<GenreViewModel> Genres { get; set; }
    }
}

WebUI/Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Application.Interfaces;
using AutoMapper;
using Domain.Models;
using Filmes.WebApp.Configuration;
using Infrastructure.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebUI.Models;

namespace MvcMovie.Controllers
{
    public class GenreController : MainController
    {
        private readonly ILogger<GenreController> _logger;
        private readonly IGenreService _genreService;

        public GenreController(IGenreService service, IMapper mapper, ILogger<GenreController> logger, INotifyService notificacao) : base(mapper, notificacao)
        {
            _logger = logger;
            _genreService = service;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<GenreViewModel>>(await _genreService.GenresAll()));            
        }

        public IActionResult About()
        {
            
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Browse(Guid id)
        {
            var genreModel = await _genreService.FindById(id);
            string genreName = genreModel.Name;
            string genreDescription = genreModel.Description;
            var movieList = await _genreService.ListGenreMovie(genreName);
            var viewModel = _mapper.Map<IEnumerable<MovieViewModel>>(movieList);

            var result = new GenreViewModel(genreName, genreDescription, viewModel);

            return View(result);
        }
    }
}

WebUI/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain.Models;
using Infrastructure.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using Filmes.WebApp.Configuration;
using Application.Interfaces;
using AutoMapper;
using WebUI.Models;
using System.IO;
using System.Diagnostics;
using System.Collections;
using WebUI.Utilities;

namespace WebUI.Controllers
{
    public class MovieController : MainController
    {
        private readonly IMovieService _movieService;

        public MovieController(IMapper mapper, IMovieService movieServico, INotifyService notification)
                                : base(mapper, notification)
        {
            _movieService = movieServico;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {            
            var movies = _mapper.Map<IEnumerable<MovieViewModel>>(await _movieService.MoviesAll());            

            return View(movies);
        }

        [AllowAnonymous]
        public async Task<IActionResult> IndexFilter(string sortOrder, Guid? SelectedGenre, string searchString, int? pageNumber, string currentFilter)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["GrossSortParm"] = sortOrder == "Gross" ? "gross_desc" : "Gross";
            ViewData["RatingSortParm"] = sortOrder == "Rating" ? "rate_desc" : "Rating";
            ViewData["CurrentFilter"] = searchString;
            var genreViewModel = _mapper.Map<IEnumerable<GenreViewModel>>(await _movieService.ListGenres());
            ViewBag.SelectedGenre = new SelectList(genreViewModel, "GenreID", "Name", SelectedGenre);

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                var movieSearch = _mapper.Map<IEnumerable<MovieViewModel>>(_movieService.SearchString(searchString, SelectedGenre));
                return View(movieSearch);
            }

            var sort = await _movieService.SortFilter(sortOrder);
            var result = _mapper.Map<List<MovieViewModel>>(sort);

            int pageSize = 5;

            return View(await PaginatedList<MovieViewModel>.CreateAsync(result, pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(Guid id)
        {
            var movie = await _movieService.FindById(id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(_mapper.Map<MovieViewModel>(movie));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Edit(Guid id)
        {
            var movie = await _movieService.FindById(id);
            if (movie == null)
            {
                return NotFound();
            }
            MovieViewModel viewModel = new MovieViewModel { };

            await MappingListGenres(viewModel);
            ViewBag.GenreID = new SelectList(viewModel.Genres, "GenreID", "Name", movie.GenreID);
            return View(_mapper.Map<MovieViewModel>(movie));
        }

        // POST: Movie/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [AllowAnonymous]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> EditConfirmed(MovieViewModel viewModel)
        {
            if (!ModelState.IsValid) return View(await MappingListGenres(viewModel));            
            
            if (viewModel.ImageUpload != null)
            {
                string path = string.Empty;
                var movie = await _movieService.FindImagePath(viewModel.ID);
                if (movie != null)
                {
                    var oldPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", movie);
                    if (System.IO.File.Exists(oldPath))
                    {
                        System.IO.File.Delete(oldPath);
                    }
                }
                path = Guid.NewGuid().ToString() + Path.GetExtension(viewModel.ImageUpload?.FileName);

                if (UpdateFile(viewModel.ImageUpload, path).Result)
                {
                    viewModel.ImagePath = path;
                }
            }

            await _movieService.Update(_mapper.Map<Movie>(viewModel));

            if (!ValidOperation())
            {
                return View(await MappingListGenres(viewModel));
            }

            if (_notification.HasError()) return RedirectToAction(nameof(Error));

            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Create()
        {
            var result = new MovieViewModel();

            return View(await MappingListGenres(result));
        }

        [HttpPost]
        [AllowAnonymous]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create(MovieViewModel viewModel)
        {
            if (!ModelState.IsValid) return View(await MappingListGenres(viewModel));

            string path = string.Empty;

            if (viewModel.ImageUpload.Length > 0)
            {
                path = Guid.NewGuid().ToString() + Path.GetExtension(viewModel.ImageUpload?.FileName);
            }

            if (UploadFile(viewModel.ImageUpload, path).Result)
            {
                viewModel.ImagePath = path;
            }

            await _movieService.Insert(_mapper.Map<Movie>(viewModel));

            if (!ValidOperation())
            {
                return View(await MappingListGenres(viewModel));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Delete(Guid id)
        {
            var movie = await _movieService.FindById(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(_mapper.Map<MovieViewModel>(movie));
        }

        // POST: Movie/Delete/5
        [HttpPost]
        [AllowAnonymous]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var movie = await _movieService.FindById(id);

            if (movie != null)
            {
                var viewModel = _mapper.Map<MovieViewModel>(movie);
                if (viewModel.ImageUpload != null)
                {
                    if (System.IO.File.Exists(viewModel.ImagePath))
                    {
                        System.IO.File.Delete(viewModel.ImagePath);
                    }
                }
            }


            await _movieService.Remove(id);



            if (_notification.HasError()) return RedirectToAction(nameof(Error));

            return RedirectToAction(nameof(Index));
        }

        private async Task<MovieViewModel> MappingListGenres(MovieViewModel viewModel)
        {
            viewModel.Genres = _mapper.Map<IEnumerable<GenreViewModel>>(await _movieService.ListGenres());
            return viewModel;
        }

        private async Task<bool> UploadFile(IFormFile imageUpload, string imgPath)
        {
            if (imageUpload == null || imageUpload?.Length == 0)
            {
                return false;
            }

            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", imgPath);

            if (System.IO.File.Exists(path))
            {
                return false;
            }

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await imageUpload.CopyToAsync(stream);
            }
            return true;
        }

        private async Task<bool> UpdateFile(IFormFile imageUpload, string imgPath)
        {
            if (imageUpload == null || imageUpload?.Length == 0)
            {
                return false;
            }

            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", imgPath);

            if (System.IO.File.Exists(path))
            {
                return false;
            }

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await imageUpload.CopyToAsync(stream);
            }
            return true;
        }

        [AllowAnonymous]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebUI/Extensions/ViewComponents/SummaryViewComponent.cs
using Application.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebUI.Extensions.ViewComponents
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly INotifyService _notifiyService;

        public SummaryViewComponent(INotifyService notifyServico)
        {
            _notifiyService = notifyServico;
        }

        public IViewComponentResult Invoke()
        {
            var notifications = _notifiyService.AllErrors().Select(x => x.Error).ToList();

            notifications.ForEach(x => ViewData.ModelState.AddModelError(string.Empty, x + " <br />"));

            return View(notifications);
        }
    }
}

WebUI/Views/Movie/Create.cshtml
@model MovieViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Movie</h4>
<hr />

<vc:summary></vc:summary>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Director" class="control-label"></label>
                <input asp-for="Director" class="form-control" />
                <span asp-validation-for="Director" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gross" class="control-label"></label>
                <input asp-for="Gross" class="form-control" />
                <span asp-validation-for="Gross" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" type="number"/>
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreID" class="control-label"></label>
                <select asp-for="GenreID" class="form-control" asp-items="@(new SelectList(Model.Genres,"GenreID","Name"))">
                    <option>Selecionar</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ImageUpload" class="control-label"></label>
                <input asp-for="ImageUpload" type="file" class="form-control" />
                <span asp-validation-for="ImageUpload" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script>
        $(function () {
            $("#ReleaseDate").datepicker({ showOn: "button", buttonImage: "../../images/calendar.gif", buttonImageOnly: true, buttonText: "Select date" });
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebUI/Views/Movie/Delete.cshtml
@model MovieViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Director)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Director)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gross)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gross)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
    </dl>
    
    <form asp-action="DeleteConfirmed" method="post">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebUI/Views/Movie/Details.cshtml
@model MovieViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Director)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Director)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gross)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gross)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            <img src="~/images/@Model.ImagePath" class="rounded float-left" width="200" height="200" alt="...">
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebUI/Views/Movie/Edit.cshtml
@model MovieViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Director" class="control-label"></label>
                <input asp-for="Director" class="form-control" />
                <span asp-validation-for="Director" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gross" class="control-label"></label>
                <input asp-for="Gross" class="form-control" />
                <span asp-validation-for="Gross" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreID" class="control-label"></label>
                <select asp-for="GenreID" class="form-control" asp-items="ViewBag.GenreID"><option>Select</option></select>
                
                <span asp-validation-for="GenreID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUpload" class="control-label"></label>
                <input asp-for="ImageUpload" type="file" class="form-control" />
                <span asp-validation-for="ImageUpload" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebUI/Views/Movie/GenreMenu.cshtml
@model IEnumerable<Domain.Models.Genre>


<div class="container">
    <div class="btn-group btn-group-justified">
        @foreach (var genre in Model)
        {
            @Html.ActionLink(genre.Name, "Browse", "Movie", new { Genre = genre.Name }, new { @class = "btn btn-primary" })
        }
        @Html.ActionLink("More...", "Index", "Genre", null, new { @class = "btn btn-primary" })
    </div>
</div>

WebUI/Views/Movie/Index.cshtml
@model IEnumerable<MovieViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a> | 
    <a asp-action="IndexFilter">Filter Movies</a>
</p>




<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ImagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Director)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gross)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                <img src="~/images/@item.ImagePath" class="rounded float-left" width="40" height="40" alt="...">
            </td>
            <td>
                @Html.ActionLink(item.Title, "Details", "Movie", new { id = item.ID }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Director)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gross)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre.Name)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> | 
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

WebUI/Views/Movie/IndexFilter.cshtml
@model WebUI.Utilities.PaginatedList<MovieViewModel>

@{
    ViewData["Title"] = "IndexFilter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>IndexFilter</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-action="IndexFilter" method="get">
    <div class="form-actions no-color">
        <p>
            Find by Title or Director: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-dark" />
            Select Genre: @Html.DropDownList("SelectedGenre", "All")
            <input type="submit" value="Filter" class="btn btn-dark" />|
            <a asp-action="IndexFilter">Back to Full List</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>

            <th>
                Picture
            </th>
            <th>
                <a asp-action="IndexFilter" asp-route-sortOrder="@ViewData["NameSortParm"]">Title</a>
            </th>
            <th>
                <a asp-action="IndexFilter" asp-route-sortOrder="@ViewData["DateSortParm"]">Release Date</a>
            </th>
            <th>
                Director
            </th>
            <th>
                <a asp-action="IndexFilter" asp-route-sortOrder="@ViewData["GrossSortParm"]">Gross</a>
            </th>
            <th>
                <a asp-action="IndexFilter" asp-route-sortOrder="@ViewData["RatingSortParm"]">Rating</a>
            </th>
            <th>
                Genre
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="~/images/@item.ImagePath" class="rounded float-left" width="40" height="40" alt="...">
                </td>
                <td>
                    @Html.ActionLink(item.Title, "Details", "Movie", new { id = item.ID }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReleaseDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Director)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gross)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre.Name)
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="IndexFilter"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="IndexFilter"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>